DROP TABLE IF EXISTS teams CASCADE;

CREATE TABLE teams (
  id serial PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE
);